"""update models relationship

Revision ID: 4ef5e22e5666
Revises: d488400bbf91
Create Date: 2021-04-24 17:11:31.642230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef5e22e5666'
down_revision = 'd488400bbf91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
